### PR TITLE
Use relative path

### PR DESCRIPTION
**Pull request by snmishra**
Fix for #38 

Add option to for treating paths in command line as relative to baseline file path, even when given as absolute path.

### CODE REVIEW

**Comment by jarojasm95** [comment]
this looks good to me, thanks for the contribution!

I am noticing that tests are not running because of the recent change to `main` branch, I will fix that and then come back to this when tests are running

**Comment by snmishra** [comment]
I did get a note from @pwoolvett, but don't see the discussion here.
> to consider:
>   - flakeheaven/_logic/_baseline.py -> check whether Path(path).is_absolute() -> use .relative_to with either pyproject.toml's parent folder or Path.cwd()
>   - if relative_to fails, meaning its outside of the project, keep it absolute.

I haven't figured out how to do that yet. Do you want to for that or think the PR is good as is @jarojasm95 ?

**Comment by jarojasm95** [comment]
I've updated the `main` branch with the updated CI workflow, please update your branch

I'll defer to @pwoolvett on the feedback you're mentioning

**Comment by snmishra** [comment]
Thanks @pwoolvett! Rebased and pushed. Needs approval to run workflows

**Review by mcarans — APPROVED** [review]
This looks fine to me. Thanks for the contribution.

**Comment by pwoolvett** [comment]
@snmishra 

https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to

added in python3.9

**Comment by mcarans** [comment]
Seems it's necessary to approve each run of the tests. I have done so and now the issue is:
```
  . ./.venv/bin/activate  # use venv created by poetry
  isort --check flakeheaven
  shell: sh -e {0}
  env:
    POETRY_VIRTUALENVS_CREATE: true
    POETRY_VIRTUALENVS_IN_PROJECT: true
ERROR: /__w/flakeheaven/flakeheaven/flakeheaven/formatters/_baseline.py Imports are incorrectly sorted and/or formatted.
```

**Comment by snmishra** [comment]
> @snmishra
> 
> https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to
> 
> added in python3.9
> 
> I assume the other checks would've failed anyway because of it...

@pwoolvett and @mcarans Hopefully tests should pass this time.

**Comment by mcarans** [comment]
@snmishra nearly there, just some lint issues:
```
flakeheaven/_patched/_app.py:57:121: E501 line too long (136 > 120 characters) [pycodestyle]
  group.add_argument('--relative', action='store_true', help='Treat file paths as relative to directory containing baseline file')
                                                                                                                  ^
flakeheaven/_patched/_checkers.py:44:36: Q000 Double quotes found but single quotes preferred [flake8-quotes]
  self.relative = kwargs.pop("relative", False)
                             ^
flakeheaven/_patched/_checkers.py:2[9](https://github.com/flakeheaven/flakeheaven/runs/5060867845?check_suite_focus=true#step:6:9):1: E302 expected 2 blank lines, found 1 [pycodestyle]
  def is_relative_to(path: Path, maybe_parent: Path):
  ^
flakeheaven/_patched/_checkers.py:37:1: E302 expected 2 blank lines, found 1 [pycodestyle]
  class FlakeHeavenCheckersManager(Manager):
```

**Comment by mcarans** [comment]
All good with me. @pwoolvett ?

**Comment by pwoolvett** [comment]
Thanks  @snmishra !

**Pull request merged**
