### PR TITLE
feat(lint): enable flag to check for missing plugins

### LINKED ISSUE #139: Feature Request: Enforce "more checks and reproducibility" on the `pre-commit` hook
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- Run `flakeheaven missing` additionally on `pre-commit` (you cannot run it separately, as the `venv` where `flakeheaven` is running is exclusive to itself)
- Run `flakeheaven config` additionally on `pre-commit` (can assist on reproducibility of the CI / pre-commit job. Can be ran only "when CI is detected" or when `--ci` is passed / consumed on `flakeheaven lint`)

_All of the above_ can be considered as additional flags passed/consumed on `flakeheaven lint`, _or_ we can create a new wrapper `flakeheaven pre-commit` as a thin wrapper around `flakeheaven lint --pre-commit --ci`

**Describe alternatives or workarounds you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by pwoolvett**
* [x] check why pylint shows missing
* [x] add tests

fixes #139

### CODE REVIEW

**Comment by pwoolvett** [comment]
ping @mcarans @jarojasm95

**Comment by pwoolvett** [comment]
> Thanks for working on this feature @pwoolvett. I get test failures (running directly in PyCharm and using ~/.local/bin/poetry run pytest tests (after a fresh poetry install). `tests/test_commands/test_config.py F..... `
> 
> It seems to be "optional arguments:\n" vs "options:\n" and also an additional "\n\x1b[0m" in tests/test_commands/test_config.py:52. I can see the checks have passed in the PR. I guess you're not seeing this error?

Must be related to color escape codes / colorama

Thanks

I guess we have to add windows to ci

**Comment by mcarans** [comment]
> > Thanks for working on this feature @pwoolvett. I get test failures (running directly in PyCharm and using ~/.local/bin/poetry run pytest tests (after a fresh poetry install). `tests/test_commands/test_config.py F..... `
> > It seems to be "optional arguments:\n" vs "options:\n" and also an additional "\n\x1b[0m" in tests/test_commands/test_config.py:52. I can see the checks have passed in the PR. I guess you're not seeing this error?
> 
> Must be related to color escape codes / colorama
> 
> Thanks
> 
> I guess we have to add windows to ci

I'm using Linux Mint.

**Comment by pwoolvett** [comment]
@mcarans 

* the "optional arguments:\n" vs "options:\n"  things is because of the python version 3.10:
```console
$ py39 -c "from argparse import ArgumentParser as a;a().parse_args()" --help
usage: -c [-h]

optional arguments:
  -h, --help  show this help message and exit
$ py310 -c "from argparse import ArgumentParser as a;a().parse_args()" --help
usage: -c [-h]

options:
  -h, --help  show this help message and exit
```

* I don't know about the color escape codes, but you mention it happened only with `tests/test_commands/test_config.py`, right? This PR does not touch that test, only `tests/test_patched/test_app.py`...

**Review by mcarans — APPROVED** [review]
Since the issues I see are unrelated to your changes, I'll go ahead and approve

**Comment by pwoolvett** [comment]
Thanks @mcarans for taking the time

**Pull request merged**
