### PR TITLE
Change merge configs to avoid creating empty values

### PR DESCRIPTION
**Pull request by FSuman**

### CODE REVIEW

**Comment by FSuman** [comment]
Fixes #114

**Comment by pwoolvett** [comment]
hi @FSuman , thanks for your contribution.

It looks fine. Please

1. add testing to include this use case, so that the test would have failed without your fix.
2. rename the commit header comply with conventional commits.

**Comment by FSuman** [comment]
> hi @FSuman , thanks for your contribution.
> 
> It looks fine. Please
> 
> 1. add testing to include this use case, so that the test would have failed without your fix.
> 2. rename the commit header to comply with conventional commits.
> 3. Make sure to add type bints accordingly

Hi @pwoolvett, tests added, commit header renamed and mypy is locally happy now

**Comment by pwoolvett** [comment]
From the docs [here](https://flakeheaven.readthedocs.io/en/latest/config.html):

> By default, FlakeHeaven runs only [pyflakes](https://github.com/PyCQA/pyflakes) and [pycodestyle](https://pypi.org/project/pycodestyle/).

The defaults are set [here](https://github.com/flakeheaven/flakeheaven/blob/d91eb9ffe34103e84b65988291a1b258c1df5ffb/flakeheaven/_constants.py#L23-L26), which is what I guess you mentioned in #114 .

So this behavior was actually intended but not working. (!)

Just ran a git blame against that section of the code and it was like this for a while now. 

However, this will likely start crashing some users checks (specially in CI envs), where, without proper configuration, neither of those pugins was being executed!

One last change before the merge:  As this is a breaking change, please mark it explicitly in your second commit eg to something like this

```
fix(logic)!: properly merge configs to avoid creating empty values

fixes #114

BREAKING CHANGE: pycodestyle and pyflakes will now run when unconfigured.
```

**Comment by pwoolvett** [comment]
Thanks @FSuman , your changes have been merged and released with flakeheaven 2.0.0

**Pull request merged**
