### PR TITLE
Allow pointing to HOME with "~" tilde

### PR DESCRIPTION
**Pull request by patnr**
Enables

```toml
[tool.flakeheaven]
base = "~/.config/pyproject.toml"
```

### CODE REVIEW

**Review by pwoolvett — CHANGES_REQUESTED** [review]
* [x] please use conventional commits (feat)
* [x] Please add simple test for this case

**Comment by patnr** [comment]
Thank you for the feedback, sorry I did not check the guidelines first.

I have added a test, but it only tests a local file in a tmp dir.

I'm not sure how to go about actually testing for a `pyproject.toml` located at HOME,
since then I would clutter the developer's HOME dir.

**Comment by patnr** [comment]
Thanks a lot for the insight! Only changes needed to your code was `yield t`.

I parameterised the fixture to also test with a path outside of home (in regular tmp dir).

And expanded the comparison to compare the full resulting dicts.

BTW, I hope it's the correct approach I'm taking with force-pushing to modify the PR?

**Comment by patnr** [comment]
I added one commit that fixes an issue with the test:
Before, we created a tmpdir in HOME, but did not test if `read_config`
works _when pointed to it by the use of `~`._

**Comment by pwoolvett** [comment]
As both the test and the testfix are related to the incoming feature, could you squash everything into your first commit please? (`feat(logic): ...`)

After that we should be good

**Review by pwoolvett — APPROVED** [review]

**Comment by patnr** [comment]
Done & done!

**Comment by pwoolvett** [comment]
Thank you for your contribution!

There's an issue with the ci (something about poetry core) wivh didnt release incoming version with your feature, but kts already merges to main and will be available with next release, as soon as the ci is fixes (next week?)

**Pull request merged**
