### PR TITLE
fix(patched): re-enable --config cli arg

### LINKED ISSUE #48: Flakeheaven fails with toml config
I am trying to use flakeheaven to replace flakehell, and when I supply my pyproject.toml which has mypy overide sections (multiple sections with the same name) it fails to parse it.

```
configparser.DuplicateSectionError: While reading from 'service/pyproject.toml' [line 148]: section '[tool.mypy.overrides' already exists
```
The below is just an example.
```
[[tool.mypy.overrides]]
module = ["package1.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["package1.*"]
ignore_missing_imports = false
```

initially I had run it as follows (this is how my flakehell successfully runs)
```
/bin/bash -c 'cd service && flakeheaven lint ${@#*/} 2>/dev/null'
```

where the 2> is to silence logging errors flakehell had and the bash expansion is to remove the "service/" from the paths provided to it. This would work as it first changes dir to the directory where the toml is and flakehell picks it up automatically. But for some reason flakeheaven just silently passed with no output...

Anyway, the config seems to be an issue regardless and possible the cause of the second part.

Thanks!

### PR DESCRIPTION
**Pull request by pwoolvett**
Moved `--config` parsing for toml to `App.parse_preliminary_options` so flakehaven can extract it before flake8 uses it.

fixes #48

### CODE REVIEW

**Review by mcarans — APPROVED** [review]
Nice work! Change looks fine to me. Is there any test for passing --config with TOML?

**Comment by pwoolvett** [comment]
no, there are no additional tests... yet

**Comment by pwoolvett** [comment]
tests added @mcarans @jarojasm95

**Review by jarojasm95 — APPROVED** [review]

**Review by mcarans — COMMENTED** [review]
Super, thanks @pwoolvett, looks good!

**Pull request merged**
